### ISSUE TITLE
About the error "No such container"

### ISSUE THREAD

**Issue by fhowen** [AmedeoSapio/DAIET-HotNets17#1]
Hi,I want to try your work on my machine (Ubuntu 16.04).
I have followed the instructions in [README.md](https://github.com/AmedeoSapio/DAIET/blob/master/README.md). Everything goes well before step 9. (I saw step 8 is marked as optional and i skipped it).

Since i only have 8 cores, I have changed these two lines to specify the CPU core:
`print self.run_cmd("screen -S bmv2 -d -m docker container run --name bmv2 --cpuset-cpus=\"1,2\" --network host -v "+self.folder+":/Testbed -e CMD_LINE=\""+cmdline+"\" -ti p4lang/behavioral-model bash")`
`print self.run_cmd("screen -S h"+str(i)+" -d -m docker container run --name h"+str(i)+" -h h"+str(i)+" --cpuset-cpus=\""+"5,6"+","+"7,8"+"\" --cap-add=NET_ADMIN --cap-add=SYS_ADMIN -v "+self.folder+":/Testbed -ti openjdk bash")`
Like the code above, I assign switched to use core 1 and 2, hosts to use 5,6,7,8.
Then I execute step 9:
I get following mistakes:
![screenshot from 2018-01-19 13-51-10](https://user-images.githubusercontent.com/14502132/35136670-d7730f18-fd1f-11e7-9124-b40bddd791c7.png)
First I thought is was the time for sleep() is too short to create the container, I set this to 50 but it still goes wrong.

Thanks in advance.

**Comment by fhowen** [comment]
I think maybe this is caused by openjdk image.
Because I have test the BMV2 container ,it can print hello from bash.
![screenshot from 2018-01-19 14-04-35](https://user-images.githubusercontent.com/14502132/35136993-d35c322c-fd21-11e7-91f1-7ca3f4057e8b.png)
I followed the instruction to install openjdk and set **JAVA_HOME** and **PATH**.
are there libs else should I install for JAVA?

**Comment by fhowen** [comment]
In the list of Docker Images, I can see p4lang/behavioral-model, but no openjdk.
Do I need to install JRE ?

**Comment by fhowen** [comment]
After I docker pull the openjdk image on my ubuntu, the error still exists.

**Comment by fhowen** [comment]
After I docker pull openjdk image and change the CPU for hosts to "4,5,6,7", this fixed, Cause cpu core 8 doesn't exist.
But I found this line seems to have mistake:
`# Copy data locally`
`print self.run_cmd("docker container exec h"+str(i)+" cp -r /Testbed/simplemr /")`
I don't exactly understand it's meaning,

**Comment by AmedeoSapio** [comment]
Hi, 
yes, the `--cpuset-cpus` parameter takes core indexes starting from 0 (see [docker documentation](https://docs.docker.com/engine/reference/run/#specify-custom-cgroups)), so if you have 8 cores you should use indexes from 0 to 7.

The commands: 
``print self.run_cmd("screen -S bmv2 -d -m docker container run --name bmv2 ...``

``print self.run_cmd("screen -S h"+str(i)+" -d -m docker container run --name h"+str(i)+" -h h"+str(i)+...``

launch the docker containers inside a [screen](https://www.gnu.org/software/screen/manual/screen.html), so if you have errors, you can enter the screen with:
`screen -r bmv2` and `screen -r h1` to see the error message.

Your are right, there is a mistake in the command: 
``print self.run_cmd("docker container exec h"+str(i)+" cp -r /Testbed/simplemr /")``
The DAIET-MapReduce repo was once called simplemr, and we forgot to update Experiment.py.
Thank you for letting us now. I am updating Experiment.py. Let us know if the problem is not solved.

BTW that command is meant to copy the DAIET-MapReduce folder inside the container.
